### PR TITLE
Spelling & Parity with "Advanced NSOperations"

### PR DESCRIPTION
**Pull request by colinmcardell**
Very minor tweak to class name spelling for `OPOperationConditionMututallyExclusive`, now `OPOperationConditionMutuallyExclusive`. Also `OPOPeration.h` import now `OPOperation.h`.

Additionally, modifying some stuff in an attempt to get Operative to be more aligned with how the Advanced NSOperations classes function.
- [x] Parity on various states of an `OPOperation` (removes cancelled state as there is no cancelled state in Advanced NSOperations implementation, which ultimately makes sense)
- [x] Locking of `state` property on `OPOperation`
- [x] Less strings and more compiler safe ways of accessing keypaths
- [x] Removes the `/Pods` folder and `Podfile.lock` from the `Example` project
- [x] Implement `OPNetworkObserver`
- [x] Implement `OPBackgroundObserver`
- [x] Implement `OPReachabilityCondition`
- [x] Implement `OPRemoteNotificationCondition`
- [x] Implement `OPPhotosCondition`
- [x] Minor refactor to `OPAlertOperation` & `OPOperationConditionMutuallyExclusive` to make things a little more like Advanced NSOperations in regards to exclusiveWith class.
- [x] Documentation (estimated 70-75% complete)

### CODE REVIEW

**Comment by colinmcardell** [comment]
@Kabal It would be great if you could merge in my progress towards parity here. I've been banging on a good amount of these changes for the last 15 days and it's solid and functioning.
I'm happy to continue docs, spinning up some of the missing conditions and starting to build out some tests but I would prefer to do it on a different branch that has these changes in it.

**Comment by ghost** [comment]
Nice one!

**Comment by pronebird** [comment]
Wowzas! thanks for this @colinmcardell ! Would be good to bump the version for pod.

**Comment by colinmcardell** [comment]
:+1: NP! Agreed.

**Pull request merged**
