### PR TITLE
Block observer init

### PR DESCRIPTION
**Pull request by colinmcardell**
# Summary
- Bringing back the ability to just call `-init` on `OPBlockObserver`. Init should _not_ be marked as `NS_UNAVAILABLE` because the properties are publicly read write and one should be able to make a block observer with any combination of block events if they would like.
# Reference
- 1bd8da8

### CODE REVIEW

**Comment by pronebird** [comment]
You may omit -init since it's empty anyway.

**Comment by colinmcardell** [comment]
`-init` in included to satisfy the compiler warnings associated with defining a designated initializer that isn't the superclasses designated initializer

**Comment by pronebird** [comment]
Got it

**Comment by colinmcardell** [comment]
:beers:

**Pull request merged**
