### PR TITLE
OSX support

### PR DESCRIPTION
**Pull request by pronebird**
Commits history looks scary, but please look at file changes. 

Apart from all files being rearranged, there are few changes in `Podspec` file and `Operative.h`. 

I successfully use this branch in a console tool for OSX.

All files are organized in the following fashion:

```
.
├── Core
│   ├── Categories
│   │   ├── NSError+Operative.h
│   │   ├── NSError+Operative.m
│   │   ├── NSMutableDictionary+Operative.h
│   │   ├── NSMutableDictionary+Operative.m
│   │   ├── NSOperation+Operative.h
│   │   └── NSOperation+Operative.m
│   ├── Conditions
│   │   ├── OPNegatedCondition.h
│   │   ├── OPNegatedCondition.m
│   │   ├── OPNoCancelledDependenciesCondition.h
│   │   ├── OPNoCancelledDependenciesCondition.m
│   │   ├── OPOperationCondition.h
│   │   ├── OPOperationConditionEvaluator.h
│   │   ├── OPOperationConditionEvaluator.m
│   │   ├── OPOperationConditionMutuallyExclusive.h
│   │   ├── OPOperationConditionMutuallyExclusive.m
│   │   ├── OPReachabilityCondition.h
│   │   ├── OPReachabilityCondition.m
│   │   ├── OPSilentCondition.h
│   │   └── OPSilentCondition.m
│   ├── Observers
│   │   ├── OPBlockObserver.h
│   │   ├── OPBlockObserver.m
│   │   ├── OPOperationObserver.h
│   │   ├── OPTimeoutObserver.h
│   │   └── OPTimeoutObserver.m
│   ├── Operation\ Queue
│   │   ├── OPExclusivityController.h
│   │   ├── OPExclusivityController.m
│   │   ├── OPOperationQueue.h
│   │   └── OPOperationQueue.m
│   └── Operations
│       ├── Misc
│       │   ├── OPBlockOperation.h
│       │   ├── OPBlockOperation.m
│       │   ├── OPDelayOperation.h
│       │   ├── OPDelayOperation.m
│       │   ├── OPGroupOperation.h
│       │   └── OPGroupOperation.m
│       ├── Networking
│       │   ├── OPURLSessionTaskOperation.h
│       │   └── OPURLSessionTaskOperation.m
│       ├── OPOperation.h
│       └── OPOperation.m
├── Operative.h
└── iOS
    ├── Categories
    │   ├── UIUserNotificationSettings+Operative.h
    │   └── UIUserNotificationSettings+Operative.m
    ├── Conditions
    │   ├── OPAudioCondition.h
    │   ├── OPAudioCondition.m
    │   ├── OPLocationCondition.h
    │   ├── OPLocationCondition.m
    │   ├── OPOperationConditionUserNotification.h
    │   ├── OPOperationConditionUserNotification.m
    │   ├── OPPhotosCondition.h
    │   ├── OPPhotosCondition.m
    │   ├── OPRemoteNotificationCondition.h
    │   ├── OPRemoteNotificationCondition.m
    │   ├── OPVideoCondition.h
    │   └── OPVideoCondition.m
    ├── Observers
    │   ├── OPBackgroundObserver.h
    │   ├── OPBackgroundObserver.m
    │   ├── OPNetworkObserver.h
    │   └── OPNetworkObserver.m
    └── Operations
        ├── Misc
        │   ├── OPLocationOperation.h
        │   ├── OPLocationOperation.m
        │   ├── OPMediaPermissionOperation.h
        │   └── OPMediaPermissionOperation.m
        └── UI
            ├── OPAlertOperation.h
            └── OPAlertOperation.m
```

### CODE REVIEW

**Comment by colinmcardell** [comment]
Yeah, cool!
Looks good. I will have to pull and check it out.
Re:commit history, can you squash it to the key commits as to keep the master history a little more stream lined?

**Comment by pronebird** [comment]
@colinmcardell I wish I never had to do a force push. It should be squashed to single meaningful commit. 

I know I should have prepped a simple app for OS X but I really have no time for that now. Just create an OS X target and start using operations like you used to. Keep in mind that iOS related ops won't be compiled on OS X target.

Something like this should work with console app:

``` objc
int main(int argc, const char * argv[]) {
    @autoreleasepool {

        // create bunch of ops
        // call exit(0); when finished to quit the app

        [[NSRunLoop currentRunLoop] run];
    }
    return 0;
}
```

**Comment by pronebird** [comment]
Is there anything I can do to make it easier to test this branch? I am looking forward seeing this merged into master so I can send PRs for other cool conditions and fixes!

**Comment by colinmcardell** [comment]
This seems like a great start! I still haven't gotten around to building up any operations within an example project.
If you could resolve the merge conflicts that have popped up since the previous PR merge that would be great.

I think the idea of supporting OS X as a target should come with at the very least the basic structure of an example project with the appropriate target setup and the library imported. It would go a long way towards building out tests for OS X (and shared tests between platforms/targets), and displaying that the library does in fact support both iOS and OS X.

**Comment by pronebird** [comment]
@colinmcardell I did the automatic merge, things are back to normal with OS X branch. I'll take time to make example app and plug-in existing tests.

**Comment by colinmcardell** [comment]
This seems good. Fully functional for iOS with this restructure. Merging in.

**Comment by pronebird** [comment]
@colinmcardell yeah sorry man, no time for OS X sample app. Still fighting this race condition...

**Pull request merged**
